<?php

$permissions = [
    'administration.users.manage' => 'Create, update, deactivate, and review user accounts.',
    'administration.roles.manage' => 'Assign approved roles and maintain the role matrix.',
    'administration.configuration.manage' => 'Maintain templates, reference data, and platform settings.',
    'administration.audit.view' => 'Review security and operational audit events.',
    'administration.backup.manage' => 'Operate approved backup and restore controls.',
    'resident.view' => 'View resident and household records within assigned scope.',
    'resident.lookup' => 'Search resident records for a declared and approved operational purpose.',
    'resident.reference.view' => 'View approved purok, sitio, and address reference data.',
    'resident.reference.manage' => 'Maintain scoped purok, sitio, and address reference data.',
    'resident.create' => 'Create resident and household records within assigned scope.',
    'resident.update' => 'Update resident and household records within assigned scope.',
    'resident.status.manage' => 'Record controlled resident lifecycle-status changes.',
    'resident.duplicate.review' => 'Review and resolve possible duplicate resident records.',
    'resident.privacy.record' => 'Record versioned resident privacy-notice acknowledgements.',
    'resident.export' => 'Export approved resident and household data within assigned scope.',
    'document.view' => 'View document-service records within assigned scope.',
    'document.create' => 'Create and prepare document-service records.',
    'document.update' => 'Update document-service records before approval or release.',
    'document.approve' => 'Approve or return official barangay documents.',
    'document.export' => 'Generate or print authorized document outputs.',
    'document.template.manage' => 'Create, version, and publish approved document templates.',
    'document.requirements.check' => 'Verify required evidence before document approval.',
    'document.fee.reference' => 'Record reference-only fees and approved exemptions.',
    'document.release' => 'Record controlled release of an approved generated document.',
    'document.reprint' => 'Generate a controlled replacement revision with a reason.',
    'document.void' => 'Void an issued document with official authority and a reason.',
    'collection.view' => 'View reference-only collection records.',
    'collection.create' => 'Create reference-only collection records.',
    'collection.update' => 'Correct or void collection references with reasons.',
    'collection.certify' => 'Certify reference-only collection summaries.',
    'collection.export' => 'Export authorized collection-reference summaries.',
    'case.view' => 'View blotter or KP records within assigned and permitted scope.',
    'case.create' => 'Create blotter or KP records within assigned scope.',
    'case.update' => 'Update blotter or KP records before closure or lock.',
    'case.approve' => 'Authorize KP actions reserved to the Punong Barangay.',
    'case.export' => 'Generate authorized blotter or KP outputs.',
    'drrm.view' => 'View DRRM operational records within assigned scope.',
    'drrm.create' => 'Create DRRM operational records and reports.',
    'drrm.update' => 'Update DRRM records before approval or submission.',
    'drrm.approve' => 'Approve, return, or authorize DRRM submissions.',
    'drrm.export' => 'Generate authorized DRRM reports and submission packages.',
    'gad.view' => 'View GAD planning and reporting records.',
    'gad.create' => 'Create GAD planning and reporting records.',
    'gad.update' => 'Update GAD records before approval or submission.',
    'gad.approve' => 'Approve, return, or authorize GAD submissions.',
    'gad.export' => 'Generate authorized GAD reports and submission packages.',
    'report.view' => 'View dashboards and approved reports within assigned scope.',
    'report.export' => 'Generate authorized reports or export packages.',
    'report.review' => 'Review submitted reports without editing barangay source data.',
    'report.comment' => 'Add reviewer comments without editing barangay source data.',
];

$moduleViewPermissions = [
    'resident.view',
    'resident.lookup',
    'resident.reference.view',
    'document.view',
    'collection.view',
    'case.view',
    'drrm.view',
    'gad.view',
    'report.view',
];

$roles = [
    'system_administrator' => [
        'name' => 'System Administrator',
        'permissions' => [
            'administration.users.manage',
            'administration.roles.manage',
            'administration.configuration.manage',
            'resident.reference.manage',
            'document.template.manage',
            'administration.audit.view',
            'administration.backup.manage',
            ...$moduleViewPermissions,
        ],
    ],
    'punong_barangay' => [
        'name' => 'Punong Barangay',
        'permissions' => [
            ...$moduleViewPermissions,
            'document.approve',
            'document.export',
            'document.void',
            'collection.certify',
            'collection.export',
            'case.approve',
            'case.export',
            'drrm.approve',
            'drrm.export',
            'gad.approve',
            'gad.export',
            'report.export',
            'administration.audit.view',
        ],
    ],
    'barangay_secretary' => [
        'name' => 'Barangay Secretary',
        'permissions' => [
            'resident.view',
            'resident.lookup',
            'resident.reference.view',
            'resident.create',
            'resident.update',
            'resident.status.manage',
            'resident.duplicate.review',
            'resident.privacy.record',
            'resident.export',
            'document.view',
            'document.create',
            'document.update',
            'document.export',
            'document.requirements.check',
            'document.fee.reference',
            'document.release',
            'document.reprint',
            'case.view',
            'case.create',
            'case.update',
            'report.view',
            'report.export',
        ],
    ],
    'barangay_treasurer' => [
        'name' => 'Barangay Treasurer',
        'permissions' => [
            'document.view',
            'document.fee.reference',
            'collection.view',
            'collection.create',
            'collection.update',
            'collection.export',
            'report.view',
            'report.export',
        ],
    ],
    'sangguniang_barangay' => [
        'name' => 'Sangguniang Barangay / Kagawad',
        'permissions' => ['resident.view', 'resident.lookup', 'resident.reference.view', 'report.view'],
    ],
    'drrm_focal' => [
        'name' => 'BDRRMC / DRRM Focal',
        'permissions' => [
            'resident.view',
            'resident.lookup',
            'resident.reference.view',
            'drrm.view',
            'drrm.create',
            'drrm.update',
            'drrm.export',
            'report.view',
            'report.export',
        ],
    ],
    'gad_focal' => [
        'name' => 'GAD Focal',
        'permissions' => [
            'resident.view',
            'resident.lookup',
            'resident.reference.view',
            'gad.view',
            'gad.create',
            'gad.update',
            'gad.export',
            'report.view',
            'report.export',
        ],
    ],
    'lupon_kp_user' => [
        'name' => 'Lupon / KP User',
        'permissions' => [
            'resident.view',
            'resident.lookup',
            'resident.reference.view',
            'case.view',
            'case.create',
            'case.update',
            'case.export',
            'report.view',
        ],
    ],
    'municipal_cluster_admin' => [
        'name' => 'Municipal/City Cluster Admin',
        'permissions' => [
            'administration.configuration.manage',
            'document.template.manage',
            'resident.reference.view',
            'resident.reference.manage',
            'report.view',
            'report.export',
            'report.review',
            'report.comment',
        ],
    ],
    'municipal_reviewer' => [
        'name' => 'Municipal/City Reviewer',
        'permissions' => [
            'report.view',
            'report.export',
            'report.review',
            'report.comment',
        ],
    ],
];

return [
    'permissions' => $permissions,
    'roles' => $roles,
    'exclusive_roles' => [
        'system_administrator',
        'municipal_cluster_admin',
        'municipal_reviewer',
    ],
    'lockout' => [
        'attempts' => 5,
        'minutes' => 15,
    ],
];
